theatre/routes/routes.py
from flask import render_template, Blueprint, redirect, flash, request
from theatre.forms import UserForm
from theatre.routes.api.shared import get_plays, get_play
from theatre import models
from theatre.routes.api import admin as adminapi
from theatre.routes.route_functions import serialize_user_form

User = models.User
Reservation = models.Reservation


theatre = Blueprint("theatre", __name__)


@theatre.route("/")
def index():
    return render_template("theatre/pages/index.html")


@theatre.route("/about/")
def about():
    """
    Displays information about the site.
    """
    return render_template("theatre/pages/about.html")


@theatre.route("/plays/<int:page_num>")
def plays(page_num):
    """
    Displays the available plays to the user.
    """
    if page_num < 1:
        return render_template("theatre/pages/joke.html")
    plays = get_plays({"page": page_num})
    return render_template("theatre/pages/plays.html", plays=plays)


@theatre.route("/plays/")
def plays_page_one():
    """
    Displays the first page of the available plays to the user.
    """

    plays = get_plays({"page": 1})
    return render_template("theatre/pages/plays.html", plays=plays)


@theatre.route("/play/<int:play_number>")
def play(play_number):
    """
    Displays a single play to the user.
    """

    play = get_play(play_number)
    # This reservations query should be moved into the api in the future.
    # For now, I'm just testing.
    reservations = Reservation.query.filter_by(play=play)
    reservations = [res.seat.id for res in reservations]
    return render_template("theatre/pages/play.html", play=play,
                           reservations=reservations)


@theatre.route("/setup/", methods=["GET"])
def setup():
    """
    Handles all the post-install configuration.

    Currently, this just includes creating the administrative user.
    """

    user = User.query.filter_by(is_admin=True).first()
    form = UserForm()
    form.is_admin.data = True

    if user:
        flash("Admin user has already been made", "informational")
        return redirect("/")

    return render_template("theatre/pages/setup.html", form=form)


@theatre.route("/setup/", methods=["POST"])
def complete_setup():
    """
    Completes the setup of the administrative user by actually creating the
    user POST-ed to the URL.
    """
    # First check and see if an admin user already exists. If not, then there
    # is no reason to run this at all. Besides, if an admin user already
    # exists, then someone may be trying to do something nefarious and create
    # admin users without logging in.
    user = User.query.filter_by(is_admin=True).first()
    if user:
        flash("Admin user has already been made", "informational")
        return redirect("/")

    form = UserForm(request.form)
    form.is_admin.data = True

    user = serialize_user_form(form, 0)

    user = adminapi.create_user(user)

    if isinstance(user, dict):
        flash(user, "error")
        return render_template("theatre/pages/setup.html", form=form)

    flash("Admin created", "success")
    return redirect("/")

theatre/templates/theatre/pages/about.html
{% extends 'theatre/partials/base.html' %}

{% block main %}

<h1>About</h1>

{% endblock %}

theatre/templates/theatre/pages/index.html
{% extends 'theatre/partials/base.html' %}
{% block main %}

<h3 class="index_header">This is the index page. Congrats on making it this far. This means you set things up correctly.</h3>
    <ul>
        <li><a class="lnkmod" href="/api/admin/test">Admin API test page</a></li>
        <li><a class="lnkmod" href="/api/client/test">Client API test page</a></li>
        <li><a class="lnkmod" href="awETR3w4wtegZW#56ews">This link goes nowhere and is used as a placeholder for an unvisited link color</a></li>
    </ul>

{% endblock %}

theatre/templates/theatre/pages/joke.html
{% extends "theatre/partials/base.html" %}

{% block main %}

<p>There was a dog, walking down the street.</p>
<img src="{{url_for('static', filename='img/tests/static_test1.jpg')}}" alt="dog walking">

<p>He saw a sign on a park bench that said wet paint.</p>

<img src="{{url_for('static', filename='img/tests/static test 2.jpg')}}" alt="">

<p>...so he did.</p>
{% endblock %}

theatre/templates/theatre/pages/login.html
{% extends 'theatre/partials/base.html' %}

{% block main %}

<form class="wtform" action="/login/" method="post">
    <p class="wtform_text">Please Login</p>
    {{form.csrf_token}}
    <div class="wtform_field">
        {{form.email.label}}
        {{form.email}}
    </div>
    <div class="wtform_field">
        {{form.password.label}}
        {{form.password}}
    </div>
    <div class="wtform_field wtform_submit">
        <input class="wtsubmit" type="submit" value="Login">
    </div>
    <p class="wtform_text">Not registered? <a href="/signup/">Signup!</a></p>
</form>

{% endblock %}

theatre/templates/theatre/pages/play.html
{% extends "theatre/partials/base.html" %}

{% block main %}

<aside class="stage">
    <h1>{{play.name}}</h1>
    <h1>STAGE</h1>
    <div style="display:none;" id="play_id" play="{{play.id}}"></div>
</aside>
<section class="play_seating">
    {% if play.dates and play.times %}
        {% for seat in play.seats%}
            {% if seat.id in reservations %}
                <div seat="{{seat.id}}" date="{{play.dates[0].id}}" time="{{play.times[0].id}}" class="seat seat-reserved seat_row-{{seat.row}} seat_column-{{seat.column}}"></div>
            {% else %}
                <div seat="{{seat.id}}" date="{{play.dates[0].id}}" time="{{play.times[0].id}}" class="seat seat-available seat_row-{{seat.row}} seat_column-{{seat.column}}"></div>
            {% endif %}
        {% endfor %}
    {% else %}
    <h1>No dates or times associated with this play</h1>
    {% endif %}
</section>
<script type="module" src="{{url_for('static', filename='js/client_seat_selector.js')}}"></script>


{% endblock %}

theatre/templates/theatre/pages/plays.html
{% extends "theatre/partials/base.html" %}

{% block main %}

<h1>Currently Available Plays</h1>

<section class="plays_display">
    {% for play in plays %}
        <section class="play_display">
            <a class="play_display-clickable_header" href="{{url_for('theatre.play', play_number=play.id)}}">
            <header class="play_display-header">
                <img class="play_header-image" src="{{url_for('static', filename='img/tests/Phantom of the Opera mask.jpg')}}">
                <aside class="play_header-play_info">
                    <p class="play_display-link" href="/play/{{play.id}}">{{play.name}}</p>
                    <p>{{play.date}}</p>
                </aside>
            </header>
            </a>
            <section class="play_display-description">
                <p>{{play.description}}</p>
            </section>
        </section>
    {% endfor %}
</section>

{% endblock %}

theatre/templates/theatre/pages/setup.html
{% extends 'theatre/partials/base.html' %}

{% block main %}
<h2 class="setup_header">Admin Setup</h2>
<form class="wtform" action="/setup/" method="post">
    {{ form.csrf_token }}
    <div class="wtform_field" name="first_name">
        {{ form.first_name.label }}
        {{ form.first_name }}
    </div>
    <div class="wtform_field" name="last_name">
        {{ form.last_name.label }}
        {{ form.last_name }}
    </div>
    <div class="wtform_field">
        {{form.email.label}}
        {{form.email}}
    </div>
    <div class="wtform_field">
        {{form.address.label}}
        {{form.address}}
    </div>
    <div class="wtform_field">
        {{form.apartment.label}}
        {{form.apartment}}
    </div>
    <div class="wtform_field">
        {{form.city.label}}
        {{form.city}}
    </div>
    <div class="wtform_field">
        {{form.state.label}}
        {{form.state}}
    </div>
    <div class="wtform_field">
        {{form.zip_code.label}}
        {{form.zip_code}}
    </div>
    <div class="wtform_field">
        <p class="wtform_text">Your password must be at least 8 characters long.</p>
    </div>
    <div class="wtform_field">
        {{form.password.label}}
        {{form.password}}
    </div>
    <div class="wtform_field">
        {{form.confirmation.label}}
        {{form.confirmation}}
    </div>
    <div class="weform_field">
        {{form.submit(value="Create Admin")}}
    </div>
</form>
{% endblock main %}

theatre/templates/theatre/pages/signup.html
{% extends 'theatre/partials/base.html' %}
{% block main %}

<form class="wtform" action="/signup/" method="post">
    <p class="wtform_text">Please enter your account information.</p>
    {{ form.csrf_token }}
    <div class="wtform_field" name="first_name">
        {{ form.first_name.label }}
        {{ form.first_name }}
    </div>
    <div class="wtform_field" name="last_name">
        {{ form.last_name.label }}
        {{ form.last_name }}
    </div>
    <div class="wtform_field">
        {{form.email.label}}
        {{form.email}}
    </div>
    <div class="wtform_field">
        {{form.address.label}}
        {{form.address}}
    </div>
    <div class="wtform_field">
        {{form.apartment.label}}
        {{form.apartment}}
    </div>
    <div class="wtform_field">
        {{form.city.label}}
        {{form.city}}
    </div>
    <div class="wtform_field">
        {{form.state.label}}
        {{form.state}}
    </div>
    <div class="wtform_field">
        {{form.zip_code.label}}
        {{form.zip_code}}
    </div>
    <div class="wtform_field">
        <p class="wtform_text">Your password must be at least 8 characters long.</p>
    </div>
    <div class="wtform_field">
        {{form.password.label}}
        {{form.password}}
    </div>
    <div class="wtform_field">
        {{form.confirmation.label}}
        {{form.confirmation}}
    </div>
    <div class="weform_field">
        {{form.submit(value="Signup!")}}
    </div>
</form>
</form>

{% endblock %}

theatre/templates/theatre/pages/test.html
{% extends 'theatre/partials/base.html' %}

{% block main %}

<h1>Test completed successfully.</h1>

{% endblock %}